initial commit
GlizzyProductions/PFMCPP_Project3 pull request #1
Opened 2023-04-25 18:03 UTC by GlizzyProductions

starting the assignment

2023-04-26 06:16 UTC, matkatmusic requested changes
Complete the rest of the assignment

2023-04-27 16:05 UTC, matkatmusic requested changes

2023-04-27 16:05 UTC, matkatmusic commented on main.cpp
> +    CatFoodRobot currentCatFeeder;
Cats wouldn't own a `CatFoodRobot`.
a `CatOwner` would. 
remove this member variable
- [ ] revise

2023-04-27 16:05 UTC, matkatmusic commented on main.cpp
> +    HealthStatus annualCheckup;
an `AnnualCheckup` would provide a `HealthStatus`.  
but an `AnnualCheckup` is NOT a `HealthStatus`.  
this variable should be called `healthStatus`;
If you wanted this idea to be expressed correctly, you'd have a function like this:
```
HealthStatus goToAnnualPhysical(CollegeStudent resident);
```
where `resident` is obviously a student doctor who hasn't completed their residency yet at a hospital or clinic. 
Code represents real life concepts.  it is important that we choose names and create objects that represent real life and real life concepts.
- [ ] revise

2023-04-27 16:05 UTC, matkatmusic commented on main.cpp
> +struct EducationLevel
`EducationLevel` is a single thing.  `Education` encompasses many things.
This class should be called `Education`
- [ ] revise

2023-04-28 00:54 UTC, GlizzyProductions commented on main.cpp
> +    CatFoodRobot currentCatFeeder;
I think I understand! So I figured cats have collars so I changed the nested class to CatCollar to make things more realistic.

2023-04-28 01:05 UTC, GlizzyProductions commented on main.cpp
> +    HealthStatus annualCheckup;
point taken, I will keep this in mind moving forward.

2023-04-28 05:57 UTC, matkatmusic approved these changes

2023-04-28 05:57 UTC, merged