Part3
GlizzyProductions/PFMCPP_Project3 pull request #3
Opened 2023-05-06 11:50 UTC by GlizzyProductions

2023-05-06 18:43 UTC, matkatmusic requested changes

2023-05-06 18:43 UTC, matkatmusic commented on main.cpp
> +    countdown = msgDuration;
What is the point of initializing a variable to `0` and then assigning a value to it immediately after?
`auto countdown = msgDuration;`
- [ ] revise

2023-05-06 18:43 UTC, matkatmusic commented on main.cpp
>      whichSTD = "None";
Don't overwrite function arguments.
Function arguments convey information. When you overwrite them like you were doing here, erase that information. Do something else in this function to clear the warning about the unused variable.
- [ ] revise

2023-05-06 18:43 UTC, matkatmusic commented on main.cpp
>      colorChoice = "New Color";
Don't overwrite function arguments.
Function arguments convey information. When you overwrite them like you were doing here, erase that information. Do something else in this function to clear the warning about the unused variable.
- [ ] revise

2023-05-06 18:43 UTC, matkatmusic commented on main.cpp
>      newestDegree = "Degree Name";
Don't overwrite function arguments.
Function arguments convey information. When you overwrite them like you were doing here, erase that information. Do something else in this function to clear the warning about the unused variable.
- [ ] revise

2023-05-06 18:43 UTC, matkatmusic commented on main.cpp
>      return brokenItem;
Don't overwrite function arguments.
Function arguments convey information. When you overwrite them like you were doing here, erase that information. Do something else in this function to clear the warning about the unused variable.
- [ ] revise

2023-05-07 01:11 UTC, GlizzyProductions commented on main.cpp
>      whichSTD = "None";
I understand, I actually started wondering about this as I moved through this part of the project.

2023-05-08 04:21 UTC, matkatmusic approved these changes

2023-05-08 04:21 UTC, merged